version: "3.7"
services:
  plain:
    image: local/h1
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 5M
    environment:
      PORT: 10000
      TYPE: plain
    networks:
      - backend
  chocolate:
    image: local/h1
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 5M
    environment:
      PORT: 10000
      TYPE: chocolate
    networks:
      - backend
  strawberry:
    image: local/h1
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.10'
          memory: 5M
    environment:
      PORT: 10000
      TYPE: strawberry
    networks:
      - backend
  nginx:
    image: local/nginx
    restart: always
    ports:
      - 32345:80
    networks:
      - backend
      - frontend
  tester:
    image: local/tester
    restart: always
    networks:
      - frontend

networks:
  backend:
  frontend:
